#! /bin/python
import argparse
import windows
parser = argparse.ArgumentParser(
    prog="vault",
    formatter_class=argparse.RawTextHelpFormatter
)
parser.add_argument("operation", type=str, help="operation you wanna do")
args = parser.parse_args()

print(args.operation)